spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ertho
    driver-class-name: com.mysql.cj.jdbc.Driver

  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        ejb:
          interceptor: com.ertho.gestiondestosck.interceptor.Interceptor

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto : update
      dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8081

flickr:
  apiKey: 5a018887ed23d0a34862898d0018580e
  apiSecret: 130ec45d709bc1f1
  appKey: 72157720836025770-78b21f20cd22b006
  appSecret: f84b2d522cccfa7d

springdoc:
  api-docs:
    path=/com.ertho.gestiondestock: